version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  gw:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./gw
    ports:
    - '80:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
    - /app/node_modules
    - ./api:/app
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379 
    - PG_USER=postgres
    - PG_PASSWORD=postgres_password
    - PG_HOST=postgres
    - PG_PORT=5432
    - PG_DATABASE=postgres
    ports:
    - '5000:5000'    
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
    - /app/node_modules
    - ./frontend:/app    
    ports:
    - '3000:3000'
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
    - /app/node_modules
    - ./worker:/app
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379